<?php
use Drupal\Core\StringTranslation\StringTranslationTrait;
use GuzzleHttp\Exception\RequestException;

/**
 * Fetches data from an external API.
 *
 * @return array
 *   The API response data.
 */
function fetch_dhl_api_data($country, $city, $postal_code) {
  $client = \Drupal::httpClient();
  $url = "https://api.dhl.com/location-finder/v1/find-by-address?countryCode=".$country."&addressLocality=".$postal_code; // Replace with your API endpoint

  try {
    $response = $client->request('GET', $url, [
      'headers' => [
        'Accept' => 'application/json',
        'DHL-API-Key'=>'demo-key'
        // Add any other headers required by the API.
      ],
    ]);

    $data = json_decode($response->getBody()->getContents(), TRUE);
    return $data;
  }
  catch (RequestException $e) {
    watchdog_exception('my_custom_module', $e);
    return [];
  }
}
